# Generated by Django 5.1.2 on 2024-11-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_image_event_location_event_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('pianists', 'Pianists'), ('singers', 'Singers'), ('bassists', 'Bassists'), ('guitarist', 'Guitarist'), ('drummer', 'Drummer')], max_length=20)),
                ('bio', models.TextField()),
                ('specialty', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='media/team/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
