# Generated by Django 5.1.2 on 2024-12-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('featured', 'Featured Event'), ('upcoming', 'Upcoming Event'), ('special', 'Special Event')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('video', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('button_text', models.CharField(default='More Info', max_length=50)),
                ('button_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
