# Generated by Django 5.1.2 on 2024-12-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_announcement_date_alter_announcement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article_type', models.CharField(choices=[('news', 'News'), ('update', 'Update'), ('event', 'Event')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/')),
                ('read_more_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
